### ISSUE TITLE
python grgsm_livemon.py is missing ! 

### ISSUE THREAD

**Issue by darkhacknet** [AnarchyAngel/grgsm_livemon_for_hackrf#1]
Hey bro ! 

claearly the python grgsm_livemon.py file is not in your code, so the question is ... how did you said that this command ...

python grgsm_livemon.py -a -g 30 -f [freq]M 

will work ?

**Comment by AnarchyAngel** [comment]
You are correct the python file is not included, you will need to load this up in gnuradio and compile it, i did it that way so ppl could make their own mods and not have to worry about me putting some evil python code in it. I will update the readme to make that clear. Thank you for pointing that out.

After you compile yes it will run with the CMD you have above.

**Comment by ChillVibesMushroom** [comment]
Does this work with 4G LTE I want to use GSM Evil 2 🥺
